### ISSUE TITLE
KUBECONFIG environment variable not recognized by duplik8s

### ISSUE THREAD

**Issue by Quiwy** [Telemaco019/duplik8s#8]
When using export KUBECONFIG=/path_to/kubeconfig, it seems that duplik8s does not take the environment variable into account.

Is it possible to make duplik8s use the KUBECONFIG environment variable?

While it works with the CLI using the --kubeconfig /path_to/kubeconfig parameter, it does not work when using k9s, which relies on the KUBECONFIG environment variable. In this case, it is not possible to use duplik8s directly.

Version used : duplicate  v0.3.0

**Comment by Telemaco019** [comment]
Hi @Quiwy, thanks for raising the issue! Good point, I recently fixed the same issue in kubesafe: https://github.com/Telemaco019/kubesafe/issues/11

I'll implement this soon in duplik8s too ;)
